version: 2
jobs:
  build:
    docker:
      - image: dhawal1490/frontend
          auth:
            username: dhawal1490  # can specify string literal values
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: nginx
      - run: nginx -v
      - run: curl localhost:80 | grp "Thank you for using nginx"
      - run: ls -R ../circleci-dockerfiles
