version: 2
jobs:
  build:
    docker:
      - image: dhawal1490/frontend:v2
        auth:
          username: dhawal1490
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: echo "this is the build"
