jobs:
  build:
    docker:
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install --save
 
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build