version: 2
executor:
  nodejs:
    docker:
      - image: dhawal1490/frontend:v2
        auth:
          username: dhawal1490
          password: $DOCKERHUB_PASSWORD  
jobs:
  build:
    executor: docker
    working_directory: ~/docker-react
    steps:
      - checkout
      - run: 
          name: Echo
          command: echo "this is the"
