version: 2.1
executors:
  nodejs:
    docker:
      - image: cimg/node:14.17.0
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/dhawal1490/docker-react/environment-variables
          username: "dhawal1490"
          password: "Gunman123#"
jobs:
  build:
    executor: nodejs
    steps:
      - checkout
      - run: |
          ls
          cd docker-react


workflows:
  deploy:
    jobs:
      - build