version: 2.1

jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install --save
 
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build