version: 2
executor:
  nodejs:
    docker:
      - image: cimg/node:14.17.0
jobs:
  build:
    executor: nodejs
    working_directory: ~/docker-react
    steps:
      - checkout
      - run: 
          name: Echo
          command: echo "this is the"
