version: 2
jobs:
  build:
    docker:
      - image: dhawal1490/frontend:v1
        auth:
          username: dhawal1490
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: nginx
      - run: nginx -v
      - run: curl localhost:80 | grp "Thank you for using nginx"
      - run: ls -R ../circleci-dockerfiles
